# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 09:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pusher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdata',
            name='server_recieved',
            field=models.DateTimeField(null=True, verbose_name='Date sent'),
        ),
        migrations.AddField(
            model_name='notificationdata',
            name='server_sent',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 8, 9, 48, 26, 404100, tzinfo=utc), verbose_name='Date sent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificationdata',
            name='received',
            field=models.DateTimeField(null=True, verbose_name='Date recieved'),
        ),
        migrations.AlterField(
            model_name='notificationdata',
            name='responded',
            field=models.DateTimeField(null=True, verbose_name='Date responded'),
        ),
    ]
