# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pusher', '0002_auto_20160408_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
