# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pusher', '0002_auto_20160310_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='occupation',
            field=models.CharField(choices=[('S', 'STUDENT'), ('E', 'EMPLOYED'), ('O', 'OTHER')], default='_', max_length=1),
        ),
    ]
