# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 08:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pusher', '0003_participant_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='registered',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
