# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pusher', '0003_auto_20160310_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationdata',
            old_name='namn',
            new_name='location',
        ),
    ]
