# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pusher', '0004_participant_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdata',
            name='stress',
            field=models.IntegerField(choices=[(-1, 'choose one'), (1, 'not at all'), (2, 'just a little'), (3, 'to some extent'), (4, 'rather much'), (5, 'very much')], default=-1, max_length=1),
        ),
    ]
