# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pusher', '0004_auto_20160310_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdata',
            name='received',
            field=models.DateField(verbose_name='Date recieved'),
        ),
        migrations.AlterField(
            model_name='notificationdata',
            name='responded',
            field=models.DateField(verbose_name='Date responded'),
        ),
    ]
