# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pusher', '0005_auto_20160310_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdata',
            name='received',
            field=models.DateTimeField(verbose_name='Date recieved'),
        ),
        migrations.AlterField(
            model_name='notificationdata',
            name='responded',
            field=models.DateTimeField(verbose_name='Date responded'),
        ),
    ]
