# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pusher', '0006_auto_20160413_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationdata',
            name='location',
        ),
        migrations.AddField(
            model_name='notificationdata',
            name='busyness',
            field=models.IntegerField(choices=[(-1, 'choose one'), (1, 'not at all'), (2, 'just a little'), (3, 'to some extent'), (4, 'rather much'), (5, 'very much')], default=-1),
        ),
    ]
